/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/Permission/ActionButton.vue')['default']
    ActionButtons: typeof import('./src/components/Permission/ActionButtons.vue')['default']
    BrandIntro: typeof import('./src/components/Login/BrandIntro.vue')['default']
    CategorySection: typeof import('./src/components/ServiceHub/CategorySection.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LoginForm: typeof import('./src/components/Login/LoginForm.vue')['default']
    PageHeader: typeof import('./src/components/ServiceHub/PageHeader.vue')['default']
    PermissionDialog: typeof import('./src/components/Permission/PermissionDialog.vue')['default']
    PermissionTable: typeof import('./src/components/Permission/PermissionTable.vue')['default']
    QuickActions: typeof import('./src/components/Home/QuickActions.vue')['default']
    QuickStats: typeof import('./src/components/ServiceHub/QuickStats.vue')['default']
    Role: typeof import('./src/components/Role.vue')['default']
    RoleActionButtons: typeof import('./src/components/Role/RoleActionButtons.vue')['default']
    RoleDialog: typeof import('./src/components/Role/RoleDialog.vue')['default']
    RoleSearchForm: typeof import('./src/components/Role/RoleSearchForm.vue')['default']
    RoleTable: typeof import('./src/components/Role/RoleTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/Permission/SearchForm.vue')['default']
    ServiceCard: typeof import('./src/components/ServiceHub/ServiceCard.vue')['default']
    ServiceCategories: typeof import('./src/components/ServiceHub/ServiceCategories.vue')['default']
    ServiceGrid: typeof import('./src/components/ServiceHub/ServiceGrid.vue')['default']
    StatsCards: typeof import('./src/components/Home/StatsCards.vue')['default']
    SystemInfo: typeof import('./src/components/Home/SystemInfo.vue')['default']
    UserDialog: typeof import('./src/components/User/UserDialog.vue')['default']
    UserHeader: typeof import('./src/components/User/UserHeader.vue')['default']
    UserSearchBar: typeof import('./src/components/User/UserSearchBar.vue')['default']
    UserTable: typeof import('./src/components/User/UserTable.vue')['default']
    UserTabs: typeof import('./src/components/User/UserTabs.vue')['default']
    Welcome: typeof import('./src/components/Home/Welcome.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
